name: CI

on:
    push:
        branches:
            - "**"
        tags-ignore:
            - "v[0-9]+.[0-9]+.[0-9]+"
    pull_request:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: corepack enable
            - uses: actions/setup-node@v3
              with:
                  node-version: "22.12.0"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run unit tests
              run: pnpm test:unit
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - run: corepack enable
            - uses: actions/setup-node@v3
              with:
                  node-version: "22.12.0"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint
