on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
name: Release

permissions:
    contents: write
    pull-requests: write

run-name: Release ${{ github.ref_name }}

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: corepack enable
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.12.0"
                  cache: "pnpm"
                  registry-url: https://registry.npmjs.org
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Test
              run: pnpm test
            - name: Build project
              run: pnpm build
            - name: Create Github release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ github.ref_name }}
                  skipIfReleaseExists: true
                  generateReleaseNotes: true
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish to npm
              run: pnpm publish --no-git-checks --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
